<?php

namespace Database\Seeders;

use App\Models\Ticket;
use Illuminate\Database\Seeder;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        Ticket::insert([
            [
                'ticket_number' => 'TK-2847',
                'customer_name' => 'Sarah Johnson',
                'customer_email' => 'sarah@techcorp.com',
                'subject' => 'Unable to login',
                'description' => 'Customer reports login failure after password reset.',
                'category' => 'Auth',
                'priority' => 'CRITICAL',
                'response_minutes' => 5,
                'status' => 'OPEN',
                'agent_id' => 1,
                'resolved_at' => null,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subMinutes(2),
            ],
            [
                'ticket_number' => 'TK-2846',
                'customer_name' => 'James Williams',
                'customer_email' => 'james@example.com',
                'subject' => 'Payment failed',
                'description' => 'Customer was charged twice for the same subscription.',
                'category' => 'Billing',
                'priority' => 'HIGH',
                'response_minutes' => 10,
                'status' => 'PENDING',
                'agent_id' => 2,
                'resolved_at' => null,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subMinutes(15),
            ],
            [
                'ticket_number' => 'TK-2845',
                'customer_name' => 'Emma Davis',
                'customer_email' => 'emma@design.io',
                'subject' => 'Feature: dark mode',
                'description' => 'Customer suggests adding a dark mode option.',
                'category' => 'Feature',
                'priority' => 'LOW',
                'response_minutes' => 30,
                'status' => 'PENDING',
                'agent_id' => 3,
                'resolved_at' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subHour(),
            ],
            [
                'ticket_number' => 'TK-2844',
                'customer_name' => 'Robert Martinez',
                'customer_email' => 'robert@corp.com',
                'subject' => 'App crashes on startup',
                'description' => 'Reported crash when finalizing payment on mobile app.',
                'category' => 'Bug',
                'priority' => 'CRITICAL',
                'response_minutes' => 8,
                'status' => 'IN PROGRESS',
                'agent_id' => 1,
                'resolved_at' => null,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subHours(2),
            ],
            [
                'ticket_number' => 'TK-2843',
                'customer_name' => 'Jennifer Lee',
                'customer_email' => 'jen@startup.co',
                'subject' => 'Dashboard loads slow',
                'description' => 'Reported crash when finalizing payment on mobile app.',
                'category' => 'Perf.',
                'priority' => 'HIGH',
                'response_minutes' => 15,
                'status' => 'PENDING',
                'agent_id' => 4,
                'resolved_at' => null,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subHours(3),
            ],
            [
                'ticket_number' => 'TK-2842',
                'customer_name' => 'David Wilson',
                'customer_email' => 'david@agency.co',
                'subject' => 'PDF export broken',
                'description' => 'Download button unresponsive on billing page.',
                'category' => 'Technical',
                'priority' => 'MEDIUM',
                'response_minutes' => 20,
                'status' => 'RESOLVED',
                'agent_id' => 5,
                'resolved_at' => now()->subDays(3),
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subHours(5),
            ],
            [
                'ticket_number' => 'TK-2841',
                'customer_name' => 'Amanda Thompson',
                'customer_email' => 'amanda@blog.com',
                'subject' => 'Slack integration issue',
                'description' => 'Integration fails to sync notifications.',
                'category' => 'Integration',
                'priority' => 'HIGH',
                'response_minutes' => 12,
                'status' => 'OPEN',
                'agent_id' => 6,
                'resolved_at' => null,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subHours(8),
            ],
            [
                'ticket_number' => 'TK-2840',
                'customer_name' => 'Christopher Harris',
                'customer_email' => 'chris@shop.com',
                'subject' => 'Invoice not received',
                'description' => 'Customer never received their monthly invoice.',
                'category' => 'Billing',
                'priority' => 'MEDIUM',
                'response_minutes' => 18,
                'status' => 'RESOLVED',
                'agent_id' => 2,
                'resolved_at' => now()->subDays(4),
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
            ],
        ]);
    }
}