<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Ticket;
use App\Models\Agent;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        // Kunin ang mga totoong agent mula sa agents table (base sa pangalan)
        $agents = Agent::pluck('id', 'name');

        $tickets = [
            [
                'ticket_number' => 'TK-2847',
                'customer_name' => 'Sarah Johnson',
                'customer_email' => 'sarah@techcorp.com',
                'subject' => 'Unable to login',
                'sub_subject' => 'Authentication',
                'category' => 'Auth',
                'agent' => 'Kyle Dominick',
                'priority' => 'CRITICAL',
                'status' => 'OPEN',
                'response_minutes' => 15,
            ],
            [
                'ticket_number' => 'TK-2846',
                'customer_name' => 'James Williams',
                'customer_email' => 'james@example.com',
                'subject' => 'Payment Failed',
                'sub_subject' => 'Billing',
                'category' => 'Billing',
                'agent' => 'Taylee',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 20,
            ],
            [
                'ticket_number' => 'TK-2845',
                'customer_name' => 'Emma Davis',
                'customer_email' => 'emma@design.io',
                'subject' => 'Feature: dark mode',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Benju',
                'priority' => 'LOW',
                'status' => 'PENDING',
                'response_minutes' => 13,
            ],
            [
                'ticket_number' => 'TK-2844',
                'customer_name' => 'Robert Martinez',
                'customer_email' => 'robert@corp.com',
                'subject' => 'App crashes on startup',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Jake',
                'priority' => 'CRITICAL',
                'status' => 'OPEN',
                'response_minutes' => 12,
            ],
            [
                'ticket_number' => 'TK-2843',
                'customer_name' => 'Jennifer Lee',
                'customer_email' => 'jlee@startup.co',
                'subject' => 'Dashboard loads slow',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Kyle Dominick',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 17,
            ],
            [
                'ticket_number' => 'TK-2842',
                'customer_name' => 'David Wilson',
                'customer_email' => 'david@agency.co',
                'subject' => 'PDF export broken',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Taylee',
                'priority' => 'MEDIUM',
                'status' => 'RESOLVED',
                'response_minutes' => 18,
            ],
            [
                'ticket_number' => 'TK-2841',
                'customer_name' => 'Amanda Thompson',
                'customer_email' => 'amanda@tag.com',
                'subject' => 'Slack integration issue',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Benju',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 13,
            ],
            [
                'ticket_number' => 'TK-2840',
                'customer_name' => 'Christopher Harris',
                'customer_email' => 'chris@corp.com',
                'subject' => 'Invoice not received',
                'sub_subject' => 'Billing',
                'category' => 'Billing',
                'agent' => 'Jake',
                'priority' => 'MEDIUM',
                'status' => 'CLOSED',
                'response_minutes' => 25,
            ],
            [
                'ticket_number' => 'TK-2839',
                'customer_name' => 'Michelle Young',
                'customer_email' => 'michelle@tech.com',
                'subject' => 'Cannot reset password',
                'sub_subject' => 'Auth',
                'category' => 'Auth',
                'agent' => 'Marcus',
                'priority' => 'LOW',
                'status' => 'RESOLVED',
                'response_minutes' => 19,
            ],
            [
                'ticket_number' => 'TK-2838',
                'customer_name' => 'Olivia Brown',
                'customer_email' => 'olivia@corp.com',
                'subject' => 'Account locked after 3 attempts',
                'sub_subject' => 'Auth',
                'category' => 'Auth',
                'agent' => 'Kyle Dominick',
                'priority' => 'HIGH',
                'status' => 'OPEN',
                'response_minutes' => 12,
            ],
            [
                'ticket_number' => 'TK-2837',
                'customer_name' => 'Daniel Green',
                'customer_email' => 'daniel@billingpro.com',
                'subject' => 'Refund request not processed',
                'sub_subject' => 'Billing',
                'category' => 'Billing',
                'agent' => 'Taylee',
                'priority' => 'MEDIUM',
                'status' => 'PENDING',
                'response_minutes' => 20,
            ],
            [
                'ticket_number' => 'TK-2836',
                'customer_name' => 'Natalie Park',
                'customer_email' => 'natalie@startup.io',
                'subject' => 'Add multi-user support',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Benju',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 14,
            ],
            [
                'ticket_number' => 'TK-2835',
                'customer_name' => 'Ethan Lee',
                'customer_email' => 'ethan@services.com',
                'subject' => 'API key regeneration fails',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Jake',
                'priority' => 'CRITICAL',
                'status' => 'OPEN',
                'response_minutes' => 22,
            ],
            [
                'ticket_number' => 'TK-2834',
                'customer_name' => 'Maya Chen',
                'customer_email' => 'maya@designlab.com',
                'subject' => 'Mobile app notification bug',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Kyle Dominick',
                'priority' => 'MEDIUM',
                'status' => 'PENDING',
                'response_minutes' => 16,
            ],
            [
                'ticket_number' => 'TK-2833',
                'customer_name' => 'Noah Patel',
                'customer_email' => 'noah@techstartup.com',
                'subject' => 'Invoice PDF content incorrect',
                'sub_subject' => 'Billing',
                'category' => 'Billing',
                'agent' => 'Taylee',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 18,
            ],
            [
                'ticket_number' => 'TK-2832',
                'customer_name' => 'Lily Wong',
                'customer_email' => 'lily@enterprise.com',
                'subject' => 'Password reset email not arriving',
                'sub_subject' => 'Auth',
                'category' => 'Auth',
                'agent' => 'Marcus',
                'priority' => 'LOW',
                'status' => 'RESOLVED',
                'response_minutes' => 24,
            ],
            [
                'ticket_number' => 'TK-2831',
                'customer_name' => 'Owen Brooks',
                'customer_email' => 'owen@fintech.com',
                'subject' => 'Currency formatting update',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Benju',
                'priority' => 'MEDIUM',
                'status' => 'OPEN',
                'response_minutes' => 15,
            ],
            [
                'ticket_number' => 'TK-2830',
                'customer_name' => 'Hannah Scott',
                'customer_email' => 'hannah@marketplace.com',
                'subject' => 'Transaction history not loading',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Jake',
                'priority' => 'HIGH',
                'status' => 'IN PROGRESS',
                'response_minutes' => 21,
            ],
            [
                'ticket_number' => 'TK-2829',
                'customer_name' => 'Logan Price',
                'customer_email' => 'logan@solutions.io',
                'subject' => 'Upgrade pricing page copy',
                'sub_subject' => 'Feature',
                'category' => 'Feature',
                'agent' => 'Kyle Dominick',
                'priority' => 'LOW',
                'status' => 'CLOSED',
                'response_minutes' => 17,
            ],
            [
                'ticket_number' => 'TK-2828',
                'customer_name' => 'Chloe Wright',
                'customer_email' => 'chloe@sales.co',
                'subject' => 'Credit card update fails',
                'sub_subject' => 'Billing',
                'category' => 'Billing',
                'agent' => 'Taylee',
                'priority' => 'CRITICAL',
                'status' => 'PENDING',
                'response_minutes' => 19,
            ],
            [
                'ticket_number' => 'TK-2827',
                'customer_name' => 'Ian Brooks',
                'customer_email' => 'ian@service.com',
                'subject' => 'Data export timing issue',
                'sub_subject' => 'Technical',
                'category' => 'Technical',
                'agent' => 'Marcus',
                'priority' => 'MEDIUM',
                'status' => 'RESOLVED',
                'response_minutes' => 23,
            ],
        ];

        foreach ($tickets as $ticket) {
            $agentName = $ticket['agent'];
            unset($ticket['agent']);

            $ticket['agent_id'] = $agents[$agentName] ?? null;

            Ticket::create($ticket);
        }
    }
}
